In [9]:
import pandas as pd
import numpy as np

In [10]:
df=pd.DataFrame({
    "income":  [45000, 52000, np.nan, 61000, 45000],
    "city":    ["Kochi", "kochi", "Kochi", "Trivandrum", "Kochi"],
    "gender":  ["M", "Male", "M", "F", "M"],
})

print("Before:\n", df)

Before:
     income        city gender
0  45000.0       Kochi      M
1  52000.0       kochi   Male
2      NaN       Kochi      M
3  61000.0  Trivandrum      F
4  45000.0       Kochi      M

In [12]:
print("Rows, columns: ", df.shape)

Rows, columns:  (5, 3)

In [13]:
df.head()

    income        city gender
0  45000.0       Kochi      M
1  52000.0       kochi   Male
2      NaN       Kochi      M
3  61000.0  Trivandrum      F
4  45000.0       Kochi      M

In [14]:
df.tail()

    income        city gender
0  45000.0       Kochi      M
1  52000.0       kochi   Male
2      NaN       Kochi      M
3  61000.0  Trivandrum      F
4  45000.0       Kochi      M

In [16]:
df.dtypes

income    float64
city          str
gender        str
dtype: object

In [11]:
df.isnull().sum()

income    1
city      0
gender    0
dtype: int64

In [17]:
df['income'] = df['income'].fillna(df['income'].median())

In [19]:
df['city'].unique()

<StringArray>
['Kochi', 'kochi', 'Trivandrum']
Length: 3, dtype: str

In [20]:
df['city'] = df['city'].str.strip().str.title()

In [21]:
df['gender'] = df['gender'].replace({'Male': 'M'})

In [22]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [23]:
df= df.drop_duplicates()

In [24]:
print("After: \n", df)

After:
     income        city gender
0  45000.0       Kochi      M
1  52000.0       Kochi      M
2  48500.0       Kochi      M
3  61000.0  Trivandrum      F